import type { LeaderboardEntry, OnlinePlayer, Overview, PlayerProfileResponse } from './api';

/** Minimum displayed online count when the live server has nobody connected. */
export const DEMO_BASELINE_ONLINE = 6;

export function displayOnlineCount(real: number): number {
  return real > 0 ? real : DEMO_BASELINE_ONLINE;
}

export function resolveOverview(o: Overview): { overview: Overview; usingDemo: boolean } {
  const usingDemo = o.online_players === 0;
  return {
    overview: {
      online_players: displayOnlineCount(o.online_players),
      total_characters: o.total_characters > 0 ? o.total_characters : 2847,
      total_accounts: o.total_accounts > 0 ? o.total_accounts : 1203,
    },
    usingDemo,
  };
}

export function resolveOnlinePlayers(live: OnlinePlayer[]): { players: OnlinePlayer[]; usingDemo: boolean } {
  if (live.length > 0) return { players: live, usingDemo: false };
  return { players: DEMO_ONLINE_PLAYERS, usingDemo: true };
}

/** Shown when the game server stats API is unavailable. */
export const FALLBACK_OVERVIEW: Overview = {
  online_players: DEMO_BASELINE_ONLINE,
  total_characters: 2847,
  total_accounts: 1203,
};

export const DEMO_ONLINE_PLAYERS: OnlinePlayer[] = [
  {
    name: 'Grimjaw',
    combat_level: 61,
    hitpoints_level: 58,
    attack_level: 55,
    strength_level: 54,
    defence_level: 50,
    ranged_level: 46,
    total_level: 587,
  },
  {
    name: 'Thorne',
    combat_level: 55,
    hitpoints_level: 52,
    attack_level: 50,
    strength_level: 48,
    defence_level: 44,
    ranged_level: 41,
    total_level: 521,
  },
  {
    name: 'Aldric',
    combat_level: 42,
    hitpoints_level: 45,
    attack_level: 40,
    strength_level: 38,
    defence_level: 36,
    ranged_level: 32,
    total_level: 412,
  },
  {
    name: 'Mira',
    combat_level: 38,
    hitpoints_level: 40,
    attack_level: 35,
    strength_level: 34,
    defence_level: 33,
    ranged_level: 28,
    total_level: 368,
  },
  {
    name: 'Sera',
    combat_level: 33,
    hitpoints_level: 36,
    attack_level: 31,
    strength_level: 30,
    defence_level: 29,
    ranged_level: 27,
    total_level: 341,
  },
  {
    name: 'Elara',
    combat_level: 29,
    hitpoints_level: 32,
    attack_level: 28,
    strength_level: 27,
    defence_level: 26,
    ranged_level: 24,
    total_level: 298,
  },
];

export const DEMO_LEADERBOARD: LeaderboardEntry[] = [
  {
    name: 'Grimjaw',
    combat_level: 61,
    hitpoints_level: 58,
    attack_level: 55,
    strength_level: 54,
    defence_level: 50,
    ranged_level: 46,
    fishing_level: 28,
    farming_level: 30,
    smithing_level: 45,
    prayer_level: 40,
    magic_level: 38,
    woodcutting_level: 32,
    mining_level: 36,
    alchemy_level: 31,
    slayer_level: 44,
    survivalist_level: 35,
    total_level: 587,
    played_time: 1_200_000,
    monster_kills: 2100,
  },
  {
    name: 'Thorne',
    combat_level: 55,
    hitpoints_level: 52,
    attack_level: 50,
    strength_level: 48,
    defence_level: 44,
    ranged_level: 41,
    fishing_level: 38,
    farming_level: 35,
    smithing_level: 42,
    prayer_level: 33,
    magic_level: 36,
    woodcutting_level: 40,
    mining_level: 39,
    alchemy_level: 34,
    slayer_level: 37,
    survivalist_level: 32,
    total_level: 521,
    played_time: 864_000,
    monster_kills: 1240,
  },
  {
    name: 'Aldric',
    combat_level: 42,
    hitpoints_level: 45,
    attack_level: 40,
    strength_level: 38,
    defence_level: 36,
    ranged_level: 32,
    fishing_level: 42,
    farming_level: 44,
    smithing_level: 35,
    prayer_level: 28,
    magic_level: 30,
    woodcutting_level: 46,
    mining_level: 41,
    alchemy_level: 38,
    slayer_level: 33,
    survivalist_level: 40,
    total_level: 412,
    played_time: 540_000,
    monster_kills: 890,
  },
  {
    name: 'Mira',
    combat_level: 38,
    hitpoints_level: 40,
    attack_level: 35,
    strength_level: 34,
    defence_level: 33,
    ranged_level: 28,
    fishing_level: 50,
    farming_level: 48,
    smithing_level: 30,
    prayer_level: 25,
    magic_level: 42,
    woodcutting_level: 28,
    mining_level: 26,
    alchemy_level: 45,
    slayer_level: 29,
    survivalist_level: 38,
    total_level: 368,
    played_time: 420_000,
    monster_kills: 620,
  },
  {
    name: 'Sera',
    combat_level: 33,
    hitpoints_level: 36,
    attack_level: 31,
    strength_level: 30,
    defence_level: 29,
    ranged_level: 27,
    fishing_level: 35,
    farming_level: 38,
    smithing_level: 28,
    prayer_level: 22,
    magic_level: 26,
    woodcutting_level: 34,
    mining_level: 30,
    alchemy_level: 32,
    slayer_level: 25,
    survivalist_level: 36,
    total_level: 341,
    played_time: 360_000,
    monster_kills: 480,
  },
  {
    name: 'Elara',
    combat_level: 29,
    hitpoints_level: 32,
    attack_level: 28,
    strength_level: 27,
    defence_level: 26,
    ranged_level: 24,
    fishing_level: 40,
    farming_level: 42,
    smithing_level: 22,
    prayer_level: 20,
    magic_level: 34,
    woodcutting_level: 38,
    mining_level: 28,
    alchemy_level: 36,
    slayer_level: 22,
    survivalist_level: 42,
    total_level: 298,
    played_time: 280_000,
    monster_kills: 350,
  },
];

const DEMO_TOTAL_CHARACTERS = 2847;

const DEMO_PROFILES: Record<string, PlayerProfileResponse> = {
  Grimjaw: {
    player: DEMO_LEADERBOARD[0],
    ranks: {
      total_level: 1,
      combat_level: 1,
      hitpoints_level: 1,
      attack_level: 1,
      strength_level: 1,
      defence_level: 1,
      ranged_level: 2,
      fishing_level: 18,
      farming_level: 16,
      smithing_level: 3,
      prayer_level: 2,
      magic_level: 4,
      woodcutting_level: 12,
      mining_level: 9,
      alchemy_level: 14,
      slayer_level: 1,
      survivalist_level: 8,
      monster_kills: 1,
      played_time: 1,
    },
    total_characters: DEMO_TOTAL_CHARACTERS,
  },
  Thorne: {
    player: DEMO_LEADERBOARD[1],
    ranks: {
      total_level: 2,
      combat_level: 2,
      hitpoints_level: 2,
      attack_level: 2,
      strength_level: 2,
      defence_level: 2,
      ranged_level: 1,
      fishing_level: 11,
      farming_level: 13,
      smithing_level: 5,
      prayer_level: 6,
      magic_level: 5,
      woodcutting_level: 7,
      mining_level: 6,
      alchemy_level: 10,
      slayer_level: 4,
      survivalist_level: 11,
      monster_kills: 2,
      played_time: 2,
    },
    total_characters: DEMO_TOTAL_CHARACTERS,
  },
  Aldric: {
    player: DEMO_LEADERBOARD[2],
    ranks: {
      total_level: 3,
      combat_level: 3,
      hitpoints_level: 3,
      attack_level: 3,
      strength_level: 3,
      defence_level: 3,
      ranged_level: 3,
      fishing_level: 8,
      farming_level: 7,
      smithing_level: 9,
      prayer_level: 9,
      magic_level: 8,
      woodcutting_level: 2,
      mining_level: 4,
      alchemy_level: 6,
      slayer_level: 6,
      survivalist_level: 3,
      monster_kills: 3,
      played_time: 3,
    },
    total_characters: DEMO_TOTAL_CHARACTERS,
  },
  Mira: {
    player: DEMO_LEADERBOARD[3],
    ranks: {
      total_level: 4,
      combat_level: 4,
      hitpoints_level: 4,
      attack_level: 4,
      strength_level: 4,
      defence_level: 4,
      ranged_level: 5,
      fishing_level: 1,
      farming_level: 2,
      smithing_level: 12,
      prayer_level: 12,
      magic_level: 2,
      woodcutting_level: 15,
      mining_level: 17,
      alchemy_level: 1,
      slayer_level: 8,
      survivalist_level: 5,
      monster_kills: 4,
      played_time: 4,
    },
    total_characters: DEMO_TOTAL_CHARACTERS,
  },
  Sera: {
    player: DEMO_LEADERBOARD[4],
    ranks: {
      total_level: 5,
      combat_level: 5,
      hitpoints_level: 5,
      attack_level: 5,
      strength_level: 5,
      defence_level: 5,
      ranged_level: 4,
      fishing_level: 10,
      farming_level: 9,
      smithing_level: 14,
      prayer_level: 14,
      magic_level: 11,
      woodcutting_level: 10,
      mining_level: 11,
      alchemy_level: 8,
      slayer_level: 10,
      survivalist_level: 6,
      monster_kills: 5,
      played_time: 5,
    },
    total_characters: DEMO_TOTAL_CHARACTERS,
  },
  Elara: {
    player: DEMO_LEADERBOARD[5],
    ranks: {
      total_level: 6,
      combat_level: 6,
      hitpoints_level: 6,
      attack_level: 6,
      strength_level: 6,
      defence_level: 6,
      ranged_level: 6,
      fishing_level: 5,
      farming_level: 4,
      smithing_level: 22,
      prayer_level: 18,
      magic_level: 3,
      woodcutting_level: 4,
      mining_level: 14,
      alchemy_level: 3,
      slayer_level: 14,
      survivalist_level: 1,
      monster_kills: 6,
      played_time: 6,
    },
    total_characters: DEMO_TOTAL_CHARACTERS,
  },
};

export function getDemoPlayerProfile(name: string): PlayerProfileResponse | undefined {
  const key = Object.keys(DEMO_PROFILES).find((k) => k.toLowerCase() === name.toLowerCase());
  return key ? DEMO_PROFILES[key] : undefined;
}
